### PR TITLE
Create custom SSG for docs

### PR DESCRIPTION
**Pull request by splashsky**
Due to my constant issues and dissatisfaction with the various tools that exist, I am electing to create my own SSG for the docs. This may turn into a spin-off project as well, but for now this PR is here to track progress while I work on it.

This addresses #80 but is not going to Hugo as previously stated.

### CODE REVIEW

**Comment by Annoraaq** [comment]
A SSG is an ambitious project 🚀. So for the moment we stay with jekyll?

**Comment by splashsky** [comment]
Yeah - Jekyll will still work fine when pushing directly to the gh-pages branch, but my issue was getting it to behave when testing locally.

**Comment by Annoraaq** [comment]
I was able to set it up locally. Maybe I can help you?

**Comment by splashsky** [comment]
I appreciate it but I'll probably stick with this idea. We can continue to expand the docs as they are with Jekyll, but I have some high hopes for this generator. 😄 👍🏻

**Comment by splashsky** [comment]
Excellent! I now have a functional static site generator. It's not ready for our docs yet, but take a look over the code and see what you think. I'm open to any improvement on the current features. 😃

**Comment by splashsky** [comment]
I think this is at a point we could comfortably build the docs in it. I want to work on having it also build a basic navigation menu, but for now I think we can add entries to the nav when we put new pages in.

**Comment by splashsky** [comment]
I think since you're able to upload the docs fine I'll close this for now. This is a bigger undertaking than I thought and I'd like to continue working on a custom SSG engine in one of my own repos. When it's ready for deployment I'll head back here. 😄

**Pull request closed without merging**
